#!/usr/bin/env python
"""
check_bug_url
-------------------
The new hook is replacing the old
patchset-created.bz.0.has_bug_url hook and it based on the bz.py module.

- It checks that the bug url exist
- It checks only u/s bug urls (oVirt classification)
- It checks that the bug url is match bugzilla server (bugzilla.redhat.com)
- It checks that the bug id is correct and available

  Example 1:
  classification: oVirt
  bug url: https://bugzilla.redhat.com/1234567
  result: OK

  Example 2:
  classification: other
  bug url: https://bugzilla.redhat.com/1234567
  result: IGNORE, not relevant for 'other' classification

  Example 3:
  classification: oVirt
  bug url: https://bugzilla.redhat.com/1234567890
  result: WARN, unavailable bug id
"""

import os
import logging
import sys
import socket
import re
from config import load_config
from gerrit import Gerrit
from bz import Bugzilla
from tools import get_parser_pc
from termcolor import colored
logger = logging.getLogger(__name__)


FNAME = sys.argv[0].split("/")[-1]
S_HOOK_NAME = 'START HOOK: ' + FNAME
E_HOOK_NAME = 'END HOOK: ' + FNAME
HDR = "* Check Bug-Url"


class NotRelevant(Exception):
    """
    Customized exception for not relevant checks
    """
    def __init__(self, message):
        print_review_results(message)
        print_title(E_HOOK_NAME)
        sys.exit(0)


def init_logging(verbose=False, log_file=False):
    """
    Initialize logging

    :param verbose: boolean, if set to True setting log level to DEBUG
    :param log_file: boolean, if set to True writes logs to a file
    """
    if verbose:
        log_level = logging.DEBUG
    else:
        log_level = logging.INFO

    if log_file:
        log_name = FNAME + '.log'
        log_path = os.path.join(os.path.dirname(__file__), '..', 'logs')
        logging.basicConfig(
            filename=os.path.join(log_path, log_name),
            level=log_level,
            format=(
                '%(asctime)s::' + str(os.getpid()) +
                '::%(levelname)s::%(message)s'
            )
        )
    else:
        logging.basicConfig(
            level=log_level,
            format=(
                '%(asctime)s::' + str(os.getpid()) +
                '::%(levelname)s::%(message)s'
            )
        )


def print_review_results(
    message, cr_value='0', v_value='0',
):
    """
    Prints the review results

    :param message: the review message
    :param cr_value: code-review value
    :param v_value: verified value
    """
    review_results = "\n".join((cr_value, v_value, message))
    print review_results


def check_config(config):
    """
    Check that all the necessary configuration values are defined

    :param config: dict of configuration keys and values
    """
    not_defined_confs = [
        elem for elem
        in (
            'BZ_USER', 'BZ_PASS', 'BZ_SERVER',
            'GERRIT_SRV', 'PRODUCT', 'TRACKER_ID',
            'CLASSIFICATION',
        )
        if elem not in config
    ]

    if not_defined_confs:
        logger.error("Missing configuration values %s" % ', '.join(
            not_defined_confs
        ))
        sys.exit(1)


def print_title(title):
    """
    Prints the title with line of dashes above and below

    :param title: title name (start/end hook: <hook name>)
    """
    logger.debug(colored('-' * len(title), 'blue'))
    logger.debug(colored("{0}".format(title), 'cyan'))
    logger.debug(colored('-' * len(title), 'blue'))


def get_configuration():
    """
    Gets configuration parameters from config file

    :return: dict of config keys and values
    """
    # load the configuration file
    config = load_config()

    # check the configuration file
    check_config(config=config)

    # set bugzilla url
    config['BZ_URL'] = config['BZ_SERVER'] + '/xmlrpc.cgi'

    logger.debug("==> config: {0}".format(config))
    logger.debug("==> bz user: {0}".format(config['BZ_USER']))
    logger.debug("==> bz password: {0}".format(config['BZ_PASS']))
    logger.debug("==> bz url: {0}\n".format(config['BZ_URL']))

    return config


def set_objects(config):
    """
    Sets bugzilla and gerrit objects

    :param config: dict of configuration keys and values
    :return: bugzilla and gerrit objects
    """

    # set bugzilla object
    bz_obj = Bugzilla(
        user=config['BZ_USER'],
        passwd=config['BZ_PASS'],
        url=config['BZ_URL'],
    )

    # set gerrit object
    gerrit_obj = Gerrit(config['GERRIT_SRV'])

    return bz_obj, gerrit_obj


def get_arguments():
    """
    Get arguments

    :return: args object with all the received parameters
    """
    logger.debug("==> received params: {0}".format(sys.argv))
    parser = get_parser_pc()
    args, unknown = parser.parse_known_args()
    logger.debug("==> args: {0}\n".format(args))

    return args


def get_commit_message(gerrit_obj, commit):
    """
    Get bug urls from commit message

    :param gerrit_obj: gerrit object
    :param commit: patch commit id
    :return: string of the commit message
    """

    # get the change from commit id
    change = gerrit_obj.query(commit)[0]
    logger.debug("==> change: {0}".format(change))

    # return commit message
    return change['commitMessage']


def get_bug_urls(bz_obj, gerrit_obj, commit, bz_server):
    """
    Get bug url/s from patch commit message

    :param bz_obj: bugzilla object
    :param gerrit_obj: gerrit object
    :param commit: patch commit id
    :param bz_server: bugzilla server
    :return: list of bug urls
    """

    # get bug url\s from the commit message
    bug_urls = bz_obj.get_bug_urls(
        commit=get_commit_message(gerrit_obj=gerrit_obj, commit=commit),
        bz_server=bz_server
    )
    logger.debug("==> bug_urls: {0}".format(bug_urls))

    return bug_urls


def get_bug_info(bz_obj, bug_id):
    """
    Get bug information from the passed bug id

    :param bz_obj: bugzilla object
    :param bug_id: bug id
    :return: object with all the bug info
    """

    logger.debug("==> checking bug_id: {0}".format(bug_id))
    try:
        bug_info = bz_obj.extract_bug_info(bug_id=bug_id)
    except socket.gaierror:
        message = "{0}::WARN, failed to get bug info, ".format(HDR)
        message += "network issues. please contact infra@ovirt.org."
        print_review_results(message=message)
        sys.exit(0)

    return bug_info


def check_bug_url(bz_obj, bug_urls, branch, classifications):
    """
    Validate the bug url

    :param bz_obj: bugzilla object
    :param bug_urls: list of bug urls
    :param branch: patch branch
    :param classifications: list of classifications
    :return: tuple of message and cr_value
    """

    warn = False
    v_value = "0"
    messages = []

    if not bug_urls:
        if 'master' in branch:
            status = "IGNORE, no bug url/s found (optional for 'master' "
            status += "branch, but mandatory for 'stable' branches)"
        else:
            status = "WARN, no bug url/s found"
            warn = True

        message = "{0}::{1}".format(HDR, status)
        messages = [message]
    else:
        for bug_url in bug_urls:

            bug_id = bug_url.split("/")[-1]

            # check that we receive bug info
            bug_info = get_bug_info(bz_obj=bz_obj, bug_id=bug_id)

            if not bug_info:
                status = "WARN, unavailable bug id: {0}".format(bug_id)
                warn = True
            else:
                classification = bug_info.classification
                logger.debug("==> classification: {0}".format(classification))

                # check for 'oVirt' classification
                if classification in classifications:
                    status = "OK"
                else:
                    status = "IGNORE, not relevant for "
                    status += "'{0}' classification".format(classification)

            message = "{0}::{1}".format(HDR, status)
            messages.append(message)

    if warn:
        v_value = "-1"

    return "\n".join(messages), v_value


def main():
    """
    Main function
    """
    # initialize logging
    init_logging(verbose=True)
    print_title(S_HOOK_NAME)

    # get all passed arguments
    args = get_arguments()

    # get configuration
    config = get_configuration()

    # set bugzilla and gerrit objects
    bz_obj, gerrit_obj = set_objects(config=config)

    # get bug urls
    bug_urls = get_bug_urls(
        bz_obj=bz_obj, gerrit_obj=gerrit_obj, commit=args.commit,
        bz_server=config['BZ_SERVER'],
    )

    # check bug urls
    message, cr_value = check_bug_url(
        bz_obj=bz_obj, bug_urls=bug_urls, branch=args.branch,
        classifications=config['CLASSIFICATION'],
    )

    # prints the message and the code review value
    print_review_results(message=message, cr_value=cr_value)
    print_title(E_HOOK_NAME)


if __name__ == '__main__':
    main()
