#!/usr/bin/env python
"""
set_modified hook
-----------------
The new hook is replacing the old set_MODIFIED hook.

- It updates u/s bugs
  classifications: 'oVirt'
- It updates d/s bugs
  products: 'Red Hat Enterprise Virtualization Manager'
- It updates bug status from POST to MODIFIED only for MERGED patches
  and the bug status should be in POST state.
- It checks that all external bugs are MERGED before setting the bug status
  to MODIFIED
- It checks that the branch for the bug milestone doesn't exist
  and only then it will set the bug status to MODIFIED

Example 1:
patch status: MERGED
bug status: POST
result: OK ==> change bug status to MODIFIED

Example 2:
patch status: NEW
bug status: other (NEW|ASSIGNED|POST|MODIFIED)
result: IGNORE

Example 3:
patch status: MERGED
bug status: POST
external tracker patches status: at list one in POST
result: WARN ==> bug status won't be changed to MODIFIED
(There are still open patches)

Example 4:
patch branch: ovirt-engine-4.1
bug milestone: ovirt-4.1.1 (branch doesn't exist)
result: OK ==> change bug status to MODIFIED

Example 5:
patch branch: ovirt-engine-4.1
bug milestone: ovirt-4.1.1 (branch exist)
result: WARN ==> bug status won't be changed to MODIFIED
(detected a newer branch 'ovirt-engine-4.1.1.z' that matches the milestone)
"""
import os
import logging
import sys
import socket
import re
from config import load_config
from gerrit import Gerrit
from bz import Bugzilla
from tools import get_parser_pc, get_branches
from termcolor import colored
logger = logging.getLogger(__name__)


FNAME = sys.argv[0].split("/")[-1]
S_HOOK_NAME = 'START HOOK: ' + FNAME
E_HOOK_NAME = 'END HOOK: ' + FNAME
HDR = "* Set MODIFIED"


class NotRelevant(Exception):
    """
    Customized exception for not relevant checks
    """
    def __init__(self, message):
        print_review_results(message)
        print_title(E_HOOK_NAME)
        sys.exit(0)


def init_logging(verbose=False, log_file=False):
    """
    Initialize logging

    :param verbose: boolean, if set to True setting log level to DEBUG
    :param log_file: boolean, if set to True writes logs to a file
    """
    if verbose:
        log_level = logging.DEBUG
    else:
        log_level = logging.INFO

    if log_file:
        log_name = FNAME + '.log'
        log_path = os.path.join(os.path.dirname(__file__), '..', 'logs')
        logging.basicConfig(
            filename=os.path.join(log_path, log_name),
            level=log_level,
            format=(
                '%(asctime)s::' + str(os.getpid()) +
                '::%(levelname)s::%(message)s'
            )
        )
    else:
        logging.basicConfig(
            level=log_level,
            format=(
                '%(asctime)s::' + str(os.getpid()) +
                '::%(levelname)s::%(message)s'
            )
        )


def print_review_results(
    message, cr_value='0', v_value='0',
):
    """
    Prints the review results

    :param message: the review message
    :param cr_value: code-review value
    :param v_value: verified value
    """
    review_results = "\n".join((cr_value, v_value, message))
    print review_results


def check_config(config):
    """
    Check that all the necessary configuration values are defined

    :param config: dict of configuration keys and values
    """
    not_defined_confs = [
        elem for elem
        in (
            'BZ_USER', 'BZ_PASS', 'BZ_SERVER',
            'GERRIT_SRV', 'PRODUCTS', 'TRACKER_ID',
            'CLASSIFICATIONS',
        )
        if elem not in config
    ]

    if not_defined_confs:
        logger.error("Missing configuration values %s" % ', '.join(
            not_defined_confs
        ))
        sys.exit(1)


def print_title(title):
    """
    Prints the title with line of dashes above and below

    :param title: title name (start/end hook: <hook name>)
    """
    logger.debug(colored('-' * len(title), 'blue'))
    logger.debug(colored("{0}".format(title), 'cyan'))
    logger.debug(colored('-' * len(title), 'blue'))


def get_configuration():
    """
    Gets configuration parameters from config file

    :return: dict of config keys and values
    """
    # load the configuration file
    config = load_config()

    # check the configuration file
    check_config(config=config)

    # set bugzilla url
    config['BZ_URL'] = config['BZ_SERVER'] + '/xmlrpc.cgi'

    for option in ['CLASSIFICATIONS', 'PRODUCTS']:
        config[option] = config[option].split(',') \
            if config[option] is not None or config[option] != '' else []

    logger.debug("==> config: {0}".format(config))
    logger.debug("==> bz user: {0}".format(config['BZ_USER']))
    logger.debug("==> bz password: {0}".format(config['BZ_PASS']))
    logger.debug("==> bz url: {0}\n".format(config['BZ_URL']))

    return config


def set_objects(config):
    """
    Sets bugzilla and gerrit objects

    :param config: dict of configuration keys and values
    :return: bugzilla and gerrit objects
    """

    # set bugzilla object
    bz_obj = Bugzilla(
        user=config['BZ_USER'],
        passwd=config['BZ_PASS'],
        url=config['BZ_URL'],
    )

    # set gerrit object
    gerrit_obj = Gerrit(config['GERRIT_SRV'])

    return bz_obj, gerrit_obj


def get_arguments():
    """
    Get arguments

    :return: args object with all the received parameters
    """
    logger.debug("==> received params: {0}".format(sys.argv))
    parser = get_parser_pc()
    args, unknown = parser.parse_known_args()
    logger.debug("==> args: {0}\n".format(args))

    if 'master' in args.branch:
        message = "{0}::IGNORE, not relevant for branch: {1}".format(
            HDR, args.branch
        )
        raise NotRelevant(message)

    return args


def get_change(gerrit_obj, commit):
    """
    Get change info from commit message

    :param gerrit_obj: gerrit object
    :param commit: patch commit id
    :return: dict with change info
    """

    # get the change from commit id
    change = gerrit_obj.query(commit)[0]
    logger.debug("==> change: {0}".format(change))

    for key, value in change.items():
        if key == 'commitMessage':
            continue

        logger.debug("==> {0}: {1}".format(key, value))

    return change


def get_bug_ids(bz_obj, commit_msg, bz_server):
    """
    Get bug ids from patch commit message

    :param bz_obj: bugzilla object
    :param commit_msg: commit message string
    :param bz_server: bugzilla server
    :return: list of bug ids
    """

    # get bug url\s from the commit message
    bug_urls = bz_obj.get_bug_urls(commit=commit_msg, bz_server=bz_server)
    logger.debug("==> bug_urls: {0}".format(bug_urls))

    if not bug_urls:
        message = "{0}::IGNORE, no bug url/s found".format(HDR)
        raise NotRelevant(message)

    # get bug ids from bug urls
    bug_ids = bz_obj.get_bug_ids(bug_urls=bug_urls)
    logger.debug("==> bug_ids: {0}\n".format(bug_ids))

    return bug_ids


def get_bug_info(bz_obj, bug_id):
    """
    Get bug information from the passed bug id

    :param bz_obj: bugzilla object
    :param bug_id: bug id
    :return: object with all the bug info
    """
    reason = ''
    bug_info = None

    logger.debug("==> checking bug_id: {0}".format(bug_id))
    try:
        bug_info = bz_obj.extract_bug_info(bug_id=bug_id)

        if bug_info is None:
            reason = "(private bug or bug doesn't exist)"

    except socket.gaierror:
        reason = "(network issues). Please contact infra@ovirt.org."

    return bug_info, reason


def check_tracker(gerrit_obj, tracker_number, branch):
    """
    Check that the external tracker is MERGED by querying gerrit

    :param gerrit_obj: gerrit object
    :param tracker_number: external tracker number (gerrit patch number)
    :param branch: patch branch (i.e ovirt-engine-4.1)
    :return: bool value, True if the change is not MERGED, False otherwise
    """
    if tracker_number is None:
        return False

    changes = gerrit_obj.query(tracker_number)
    for change in changes:
        if not change.get('status'):
            continue

        # verify that the patch branch is the same as the change branch
        # to make sure that we are checking the right change
        if change.get('branch') == branch:
            change_status = change['status']
            if change_status != 'MERGED':
                return True

    return False


def check_external_trackers(trackers, gerrit_obj, change):
    """
    Check external trackers for an open patches or status other than MERGED

    :param trackers: list of trackers
    :param gerrit_obj: gerrit object
    :param change: dict with patch information
    :return: tuple of status string and warn bool value
    """
    if not trackers:
        status = "WARN, can't change bug status to MODIFIED "
        status += "(no external tracker info found)"
        return status, True

    for tracker in trackers:
        if not tracker.get('type'):
            continue

        description = tracker['type'].get('description')
        if description is None or description != 'oVirt gerrit':
            continue

        tracker_number = tracker.get('ext_bz_bug_id')
        if check_tracker(
            gerrit_obj=gerrit_obj, tracker_number=tracker_number,
            branch=change.get('branch'),
        ):
            status = "WARN, can't change bug status to MODIFIED "
            status += "(There are still open patches)"
            return status, True

    return '', False


def set_status(
        bz_obj, bug_id, change, bug_info, gerrit_obj
):
    """
    Sets bug status to 'MODIFIED' only if the current status is 'POST'

    :param bz_obj: bugzilla object
    :param bug_id: bug number
    :param change: dict with patch information
    :param bug_info: bug object
    :param gerrit_obj: gerrit object
    :return: status message string
    """
    change_status = change.get('status')
    bug_status = bug_info.status if hasattr(bug_info, 'status') else ''
    trackers = bug_info.external_bugs if hasattr(bug_info, 'external_bugs') \
        else ''

    logger.debug("==> patch status: {0}".format(change.get('status')))
    logger.debug("==> bug status: {0}\n".format(bug_status))

    if bug_status == 'POST' and change_status == 'MODIFIED':
        # if we have open patches, return warn status message
        status, warn = check_external_trackers(
            trackers=trackers, gerrit_obj=gerrit_obj, change=change
        )
        if not warn:
            # if the change branch doesn't match the bug milestone,
            # check that the branch for that milestone doesn't exist,
            # if it exist return warn status message
            status, warn = cmp_change_branch_and_bug_tm(
                bug_info=bug_info, change=change
            )
        if warn:
            return status

        try:
            bz_obj.update_bug(bug_id=bug_id, status=change_status)
            status = "OK, bug status: '{0}'".format(change_status)
        except socket.error as err:
            status = "ERROR, failed to change bug status. ({0})".format(err)
    elif bug_status == 'MODIFIED':
        status = "IGNORE, bug is already on '{0}' status".format(bug_status)
    elif bug_status != 'POST':
        status = "IGNORE, not relevant for bug status: "
        status += "'{0}'".format(bug_status)
    else:
        status = "IGNORE, not relevant for patch status: "
        status += "'{0}'".format(change_status)

    return status


def get_version_suffix(string):
    """
    Get version suffix from string

    :param string: string with
    :return: version suffix
    """
    pattern = r'\d+(\.\d)+\b'
    search_pattern = re.search(pattern=pattern, string=string)
    suffix = search_pattern.group() if search_pattern is not None else ''

    return suffix


def cmp_change_branch_and_bug_tm(bug_info, change):
    """
    Compare change branch suffix with bug target milestone suffix

    :param bug_info: bug object
    :param change: dict with patch information
    :return: tuple of status string and bool value
    """
    bm = bug_info.milestone if hasattr(bug_info, 'milestone') else ''
    logging.debug("==> bug milestone: {0}".format(bm))
    cb = change.get('branch')
    logging.debug("==> patch branch: {0}".format(cb))

    if not bm or bm == '---':
        status = "WARN, bug status won't be changed to MODIFIED "
        status += "(milestone: '{0}')".format(bm)
        return status, True

    # get bug milestone suffix version (ovirt-X.Y.Z ==> X.Y.Z)
    bm_suffix = get_version_suffix(string=bm)
    logging.debug("==> milestone suffix: {0}".format(bm_suffix))

    # get change branch suffix version (ovirt-engine-X.Y.Z ==> X.Y.Z)
    cb_suffix = get_version_suffix(string=cb)
    logging.debug("==> branch suffix: {0}".format(cb_suffix))

    # if bug milestone suffix version not equal to change brunch suffix
    # version, the bug status should be changed from POST ==> MODIFIED
    # only if the newer branch doesn't exist
    if bm_suffix != cb_suffix:

        # get all the branches for the current git project
        branches = get_branches(repo_path=os.environ['GIT_DIR'])

        nb = ''
        # check if newer branch exist
        pattern = re.compile(r'.*' + bm_suffix + r'.*')
        for branch in branches:
            search_obj = re.search(pattern, branch)
            if search_obj is not None:
                nb = search_obj.group()
                break

        if nb != '':
            status = "WARN, bug status won't be changed to MODIFIED "
            status += "(detected a newer branch '{0}' ".format(nb)
            status += "that matches the milestone)"
            return status, True

    return '', False


def update_bug_status(
        bz_obj, gerrit_obj, bug_ids, change, classifications, products,
):
    """
    Update bugs status only for the specified classification

    :param bz_obj: bugzilla object
    :param gerrit_obj: gerrit object
    :param bug_ids: list of bug ids
    :param change: dict with patch information
    :param classifications: list of classifications
    :param products: list of products
    :return: tuple of message and v_value
    """
    v_value = "0"
    messages = []

    for bug_id in bug_ids:

        bug_info, reason = get_bug_info(bz_obj=bz_obj, bug_id=bug_id)

        # if patch status is 'MERGED', replace the patch status to 'MODIFIED'
        if change.get('status') == 'MERGED':
            change['status'] = 'MODIFIED'

        classification = bug_info.classification
        logger.debug("==> classification: {0}".format(classification))
        product = bug_info.product
        logger.debug("==> product: {0}".format(product))

        if classification in classifications or product in products:
            status = set_status(
                bz_obj=bz_obj, bug_id=bug_id, change=change,
                bug_info=bug_info, gerrit_obj=gerrit_obj,
            )
        else:
            status = "IGNORE, not relevant for "
            status += "classification: '{0}'".format(classification)
            status += ", product: '{0}'".format(product)

        message = "{0}::#{1}::{2}".format(HDR, bug_id, status)
        messages.append(message)

    return "\n".join(messages), v_value


def main():
    """
    Main function
    """
    # initialize logging
    init_logging(verbose=True)
    print_title(S_HOOK_NAME)

    # get all passed arguments
    args = get_arguments()

    # get configuration
    config = get_configuration()

    # set bugzilla and gerrit objects
    bz_obj, gerrit_obj = set_objects(config=config)

    # get gerrit change
    change = get_change(gerrit_obj=gerrit_obj, commit=args.commit)

    # get bug ids
    bug_ids = get_bug_ids(
        bz_obj=bz_obj, commit_msg=change['commitMessage'],
        bz_server=config['BZ_SERVER'],
    )

    # update bug status
    message, v_value = update_bug_status(
        bz_obj=bz_obj, gerrit_obj=gerrit_obj, bug_ids=bug_ids, change=change,
        classifications=config['CLASSIFICATIONS'], products=config['PRODUCTS'],
    )

    # prints the message and the code review value
    print_review_results(message=message, v_value=v_value)
    print_title(E_HOOK_NAME)


if __name__ == '__main__':
    main()
